### ISSUE TITLE
Can't install packages directly within .Rproj

### ISSUE THREAD

**Issue by vanbenschoten** [franzbischoff/false.alarm#57]
In order to knit the Rmd files, I needed to install 'knitr' and several other packages in this .Rproj repo (I have these libraries in other. Unfortunately, there seems to be a config error in how the downloads are being launched.

---------------------
** Installing R Package Dependencies for R Markdown: 'base64enc', 'digest', 'htmltools', 'jsonlite', 'knitr', 'rmarkdown', 'tinytex'
[1/8] Installing base64enc...
Error in vapply(x, f, ..., FUN.VALUE = character(1)) : 
  values must be length 1,
 but FUN(X[[1]]) result is length 0
Calls: sourceWithProgress ... renv_install_remotes_update -> renv_description_remotes -> map_chr -> vapply
In addition: Warning messages:
1: curl: (22) The requested URL returned error: 403  
2: failed to resolve remote 'rstudio/bookdown' from project DESCRIPTION file; skipping 
3: curl: (22) The requested URL returned error: 403  
4: failed to resolve remote 'ismayc/thesisdown' from project DESCRIPTION file; skipping 
5: curl: (22) The requested URL returned error: 403  
6: failed to resolve remote 'r-lib/styler' from project DESCRIPTION file; skipping 
Traceback (most recent calls last):
8: sourceWithProgress(script = "/var/folders/kh/48n52fzs4bzcxzj89pwqq47r0000gn/T/90b0-6ef4-5b8e-85bd", 
       encoding = "UTF-8", con = stdout(), importRdata = NULL, exportRdata = NULL)
7: eval(statements[[idx]], envir = sourceEnv)
6: eval(statements[[idx]], envir = sourceEnv)
5: renv::install("base64enc")
4: renv_install_remotes_update(records, project)
3: renv_description_remotes(descpath)
2: map_chr(parsed, `[[`, "Package")
1: vapply(x, f, ..., FUN.VALUE = character(1))
Execution halted

**Comment by franzbischoff** [comment]
Try now
